#!/bin/sh

# From: <https://github.com/timvisee/update-proton-ge>
# Later forked by LucasGGamerM at <https://github.com/LucasGGamerM/update-proton-ge> to add symlink to latest support

# Stop on error
set -e

# Constants
REPO=https://github.com/GloriousEggroll/proton-ge-custom
LATEST_RELEASE_URL=$REPO/releases/latest
PROTON_DIR=~/.steam/root/compatibilitytools.d

# Find latest version tag
release_url=$(curl -Ls -o /dev/null -w %{url_effective} $LATEST_RELEASE_URL)
version=${release_url##*/}
echo Found latest version: $version

# Determine download URL and install path
download_url=https://github.com/GloriousEggroll/proton-ge-custom/releases/download/$version/$version.tar.gz
install_dir=$PROTON_DIR/Proton-GE-latest
download_file=/tmp/Proton-GE-latest.tar.gz

print_installed() {
    echo Installed versions:
    if [ -d $PROTON_DIR/Proton-GE-latest ]; then
        if [ -e $PROTON_DIR/Proton-GE-latest/.version.original ]; then
            echo "- Proton-GE-Latest -> $(cat $PROTON_DIR/Proton-GE-latest/.version.original | cut -d " " -f 2-)"
        elif [ -e $PROTON_DIR/Proton-GE-Latest/version ]; then
            echo "- Proton-GE-Latest -> $(cat $PROTON_DIR/Proton-GE-latest/version | cut -d " " -f 2-)"
        fi
    fi

    ls $PROTON_DIR | grep -e "^GE-Proton" | sed "s/^/- /"
}

rename_to_latest_version() {
    if [ -d $PROTON_DIR/Proton-GE-latest ]; then
        echo "Moving old version to $(cat $PROTON_DIR/Proton-GE-latest/.version.original | cut -d " " -f 2-)"
        sed -i 's/Proton-GE-latest/'"$(cat $PROTON_DIR/Proton-GE-latest/.version.original | cut -d " " -f 2-)"'/g' $PROTON_DIR/Proton-GE-latest/version
        sed -i 's/Proton-GE-latest/'"$(cat $PROTON_DIR/Proton-GE-latest/.version.original | cut -d " " -f 2-)"'/g' $PROTON_DIR/Proton-GE-latest/compatibilitytool.vdf
        mv $PROTON_DIR/Proton-GE-latest $(cat $PROTON_DIR/Proton-GE-latest/.version.original | cut -d " " -f 2-)
    fi

    if [ -d $PROTON_DIR/$version ]; then
        mv $PROTON_DIR/$version $PROTON_DIR/Proton-GE-latest
    fi
    if [ ! $(cat $PROTON_DIR/Proton-GE-latest/version | cut -d " " -f 2-) == Proton-GE-latest ]; then
         cp $PROTON_DIR/Proton-GE-latest/version $PROTON_DIR/Proton-GE-latest/.version.original
    fi
    sed -i 's/'"$version"'/Proton-GE-latest/g' $PROTON_DIR/Proton-GE-latest/version
    sed -i 's/'"$version"'/Proton-GE-latest/g' $PROTON_DIR/Proton-GE-latest/compatibilitytool.vdf

}

# Exit if already installed
if [ -e $install_dir/.version.original ] && [[ $(cat "$PROTON_DIR/Proton-GE-latest/version" | sed 's/ .*//') == $(cat "$PROTON_DIR/Proton-GE-latest/.version.original" | sed 's/ .*//') && $(cat $PROTON_DIR/Proton-GE-latest/.version.original | cut -d " " -f 2-) == $version ]]; then
    echo Already installed at $install_dir
    print_installed
    exit
fi

echo Downloading...
wget -q --show-progress $download_url -O $download_file

echo Extracting...
mkdir -p $PROTON_DIR
tar -xzf $download_file --directory $PROTON_DIR

echo Cleanup...
rm $download_file

rename_to_latest_version

echo Installation complete, at $install_dir
print_installed
