#!/bin/sh

# From: <https://github.com/timvisee/update-proton-ge>
# Later forked by LucasGGamerM at <https://github.com/LucasGGamerM/update-proton-ge> to add symlink to latest support

# Stop on error
set -e

# Constants
REPO=https://github.com/GloriousEggroll/proton-ge-custom
LATEST_RELEASE_URL=$REPO/releases/latest
PROTON_DIR=~/.steam/root/compatibilitytools.d

# Find latest version tag
release_url=$(curl -Ls -o /dev/null -w %{url_effective} $LATEST_RELEASE_URL)
version=${release_url##*/}
echo Found latest version: $version

# Determine download URL and install path
download_url=https://github.com/GloriousEggroll/proton-ge-custom/releases/download/$version/$version.tar.gz
install_dir=$PROTON_DIR/$version
download_file=/tmp/$version.tar.gz

print_installed() {
    echo Installed versions:
    ls $PROTON_DIR | grep -e "^GE-Proton" | sed "s/^/- /"
}

make_symlink_to_latest_version() {
    if [ ! -L $PROTON_DIR/Proton-GE-latest ] && [ -e $PROTON_DIR/Proton-GE-latest ]; then
        echo Removing existent Proton-GE-latest install...
        rm -rf $PROTON_DIR/Proton-GE-latest
    elif cmp -s $PROTON_DIR/Proton-GE-latest/version $PROTON_DIR/$version/version; then
        echo Version is identical, skipping remaking symlink...
        return
    elif [ -L $PROTON_DIR/Proton-GE-latest ]; then
        echo Removing outdated symlink...
        rm $PROTON_DIR/Proton-GE-latest
    fi

    echo Making Proton-GE-latest symlink...
    ln -s ./$version $PROTON_DIR/Proton-GE-latest
}

# Exit if already installed
if [ -d $install_dir ]; then
    echo Already installed at $install_dir
    print_installed

    echo Checking symlink...
    make_symlink_to_latest_version
    echo Finished checking Proton-GE-latest symlink integrity successfully.
    exit
fi

echo Downloading...
wget -q --show-progress $download_url -O $download_file

echo Extracting...
mkdir -p $PROTON_DIR
tar -xzf $download_file --directory $PROTON_DIR

echo Cleanup...
rm $download_file

make_symlink_to_latest_version

echo Installation complete, at $install_dir
print_installed
